//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seagull2.YuanXin.AppApi.PostSMSForDHSTSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PostSMSForDHSTSoap.PostSMSForDHSTSoap")]
    public interface PostSMSForDHSTSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVCodeSMSVerification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetVCodeSMSVerification(string mobile, string sessionId, string vcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVCodeSMSVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetVCodeSMSVerificationAsync(string mobile, string sessionId, string vcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSMSVerification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSMSVerification(string mobile, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSMSVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSMSVerificationAsync(string mobile, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFixSMSVerification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFixSMSVerification(string mobile, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFixSMSVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetFixSMSVerificationAsync(string mobile, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckVerification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckVerification(string mobile, string sessionId, string markCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckVerificationAsync(string mobile, string sessionId, string markCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendAuthenticationCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendAuthenticationCode(string mobile, string authenticationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendAuthenticationCode", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendAuthenticationCodeAsync(string mobile, string authenticationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendVerificationCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendVerificationCode(string mobile, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendVerificationCode", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendVerificationCodeAsync(string mobile, string content);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostSMSForDHSTSoapChannel : Seagull2.YuanXin.AppApi.PostSMSForDHSTSoap.PostSMSForDHSTSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostSMSForDHSTSoapClient : System.ServiceModel.ClientBase<Seagull2.YuanXin.AppApi.PostSMSForDHSTSoap.PostSMSForDHSTSoap>, Seagull2.YuanXin.AppApi.PostSMSForDHSTSoap.PostSMSForDHSTSoap {
        
        public PostSMSForDHSTSoapClient() {
        }
        
        public PostSMSForDHSTSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostSMSForDHSTSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostSMSForDHSTSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostSMSForDHSTSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVCodeSMSVerification(string mobile, string sessionId, string vcode) {
            return base.Channel.GetVCodeSMSVerification(mobile, sessionId, vcode);
        }
        
        public System.Threading.Tasks.Task<string> GetVCodeSMSVerificationAsync(string mobile, string sessionId, string vcode) {
            return base.Channel.GetVCodeSMSVerificationAsync(mobile, sessionId, vcode);
        }
        
        public string GetSMSVerification(string mobile, string sessionId) {
            return base.Channel.GetSMSVerification(mobile, sessionId);
        }
        
        public System.Threading.Tasks.Task<string> GetSMSVerificationAsync(string mobile, string sessionId) {
            return base.Channel.GetSMSVerificationAsync(mobile, sessionId);
        }
        
        public string GetFixSMSVerification(string mobile, string sessionId) {
            return base.Channel.GetFixSMSVerification(mobile, sessionId);
        }
        
        public System.Threading.Tasks.Task<string> GetFixSMSVerificationAsync(string mobile, string sessionId) {
            return base.Channel.GetFixSMSVerificationAsync(mobile, sessionId);
        }
        
        public bool CheckVerification(string mobile, string sessionId, string markCode) {
            return base.Channel.CheckVerification(mobile, sessionId, markCode);
        }
        
        public System.Threading.Tasks.Task<bool> CheckVerificationAsync(string mobile, string sessionId, string markCode) {
            return base.Channel.CheckVerificationAsync(mobile, sessionId, markCode);
        }
        
        public string SendAuthenticationCode(string mobile, string authenticationCode) {
            return base.Channel.SendAuthenticationCode(mobile, authenticationCode);
        }
        
        public System.Threading.Tasks.Task<string> SendAuthenticationCodeAsync(string mobile, string authenticationCode) {
            return base.Channel.SendAuthenticationCodeAsync(mobile, authenticationCode);
        }
        
        public string SendVerificationCode(string mobile, string content) {
            return base.Channel.SendVerificationCode(mobile, content);
        }
        
        public System.Threading.Tasks.Task<string> SendVerificationCodeAsync(string mobile, string content) {
            return base.Channel.SendVerificationCodeAsync(mobile, content);
        }
    }
}
